-- Insert the 4 missing surfboards for Hawaii Surfboard Rentals profile
INSERT INTO equipment (
  user_id,
  name,
  category,
  subcategory,
  description,
  image_url,
  price_per_day,
  price_per_week,
  location_address,
  location_lat,
  location_lng,
  size,
  weight,
  suitable_skill_level,
  status,
  visible_on_map,
  damage_deposit
) VALUES 
-- 6'6" Bonga Funshape
(
  '13ce7179-0728-472e-944f-df9f4074ef11',
  '6''6" Bonga Funshape',
  'surfboards',
  'funboard',
  'Mid: 20 3/8", Thick: 2 1/2", Fin: Tri Fin FCS. This surfboard was designed to be super fun in a variety conditions. It''s insanely fast, loose and picks up waves like a magnet. While Bonga is primarily recognized as a longboarder he rips on shortboards too! Bonga''s helped to create a board that''s all about increasing your fun factor and wave count. This rental will work well in Waikiki during a decent swell as well as on the North Shore.',
  'https://hawaiisurfboardrentals.com/wp-content/uploads/2021/01/bonga.jpg',
  50,
  160,
  'Waikiki, Honolulu, HI',
  21.278738,
  -157.82855,
  '6''6" x 20 3/8" x 2 1/2"',
  'N/A',
  'Intermediate-Advanced',
  'available',
  true,
  200
),
-- 6'4" NSP Fish
(
  '13ce7179-0728-472e-944f-df9f4074ef11',
  '6''4" NSP Fish',
  'surfboards',
  'performance shortboard',
  'Mid: 20 3/4", Thick: 2 5/8", Fin: Tri Fin. Recommended for: Intermediate to Advanced level surfers. This surfboard rental is a full-size Fish design which features a broad nose and wide body template combined with a shallow entry rocker. This wide, flat combination allows it to catch the smallest of waves. It''s generous proportion handles the bigger riders than the 6''4" length implies. Surprisingly fast and loose, it makes a perfect first shortboard or addition to your quiver. Experienced grom surfers who normally ride a shortboard may find this surfboard to work well in Waikiki or a small day on the North Shore.',
  'https://hawaiisurfboardrentals.com/wp-content/uploads/2023/04/6422-NSP-Fish.jpg',
  50,
  160,
  'Waikiki, Honolulu, HI',
  21.278738,
  -157.82855,
  '6''4" x 20 3/4" x 2 5/8"',
  'N/A',
  'Intermediate-Advanced',
  'available',
  true,
  200
),
-- 6'0" Matt Kechele Performance Module
(
  '13ce7179-0728-472e-944f-df9f4074ef11',
  '6''0" Matt Kechele Performance Module',
  'surfboards',
  'performance shortboard',
  'Nose: 10 3/4", Mid: 18 3/4", Tail: 14 1/32", Thickness: 2 1/32". A performance shortboard which will work great for an experienced adult or grom surfer. This surfboard rental is light and responsive for the North Shore swells or a decent overhead south swell for outer reef breaks in Waikiki.',
  'https://hawaiisurfboardrentals.com/wp-content/uploads/2019/03/pjimage-2-1.jpg',
  50,
  160,
  'Waikiki, Honolulu, HI',
  21.278738,
  -157.82855,
  '6''0" x 18 3/4" x 2 1/32"',
  'N/A',
  'Advanced',
  'available',
  true,
  200
),
-- 5'11" Surf Prescriptions Pro Fish
(
  '13ce7179-0728-472e-944f-df9f4074ef11',
  '5''11" Surf Prescriptions Pro Fish',
  'surfboards',
  'performance shortboard',
  'Mid: 19", Thickness: 2 3/16". A performance shortboard which will work great for an experienced adult or grom surfer. This surfboard rental is light and responsive for the North Shore swells or a decent overhead south swell for outer reef breaks in Waikiki.',
  'https://hawaiisurfboardrentals.com/wp-content/uploads/2019/03/pjimage-2-copy-5.jpg',
  50,
  160,
  'Waikiki, Honolulu, HI',
  21.278738,
  -157.82855,
  '5''11" x 19" x 2 3/16"',
  'N/A',
  'Advanced',
  'available',
  true,
  200
);;
